services:
  - type: web
    name: cuttc
    runtime: static
    buildCommand: corepack enable && corepack prepare yarn@4.9.1 --activate && yarn install --immutable && yarn build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
